# Generated by Django 5.2 on 2025-09-04 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_created_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='can_share_on_linkedin',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
