# Generated by Django 5.2.5 on 2025-09-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_can_share_on_linkedin_post_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='share_now',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
