# Generated by Django 5.2.5 on 2025-09-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_share_at_post_share_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_complete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
