# Generated by Django 5.2.5 on 2025-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_share_complete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
